register/accounts/urls.py
from django.urls import path
from . import views 

app_name='accounts'

urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name='register' ),
    path('verify/' , views.UserRegisterVerifyCodeView.as_view() , name='verify_code' ),
    path('login/' , views.UserLoginView.as_view() , name='login' ),
    path('logout/' , views.UserLogoutView.as_view() , name='logout' ),
]

register/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.Homeview.as_view() , name='home' ),
]

register/register/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('',include('home.urls',namespace='home'))
]

register/home/models.py
from django.db import models

# Create your models here.

register/home/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.

class Homeview(View):
    def get(self , request):
        return render(request , 'home.html')

register/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mysite</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .myclass{
        background-color: #ded8e6;
                
      }
    </style>
  </head>
<body class="myclass">
  
    <!--NAVBAR-->
    <nav class="navbar bg-dark navbar-dark" style="padding-top: 20px; padding-bottom:20px">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">خانه</a>
        <div class="d-flex" role="search">
          {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}"><button class="btn btn-outline-danger" type="submit">خروج</button></a>
            <a href="#"><button class="btn btn-outline-success" type="submit">خوش آمدید {{request.user.full_name}}</button></a>
            {% if request.user.is_permium %}
                <a href="#"><button class="btn btn-outline-primary" type="submit">کاربر ویژه</button></a>
            {% else %}
                <a href="#"><button class="btn btn-outline-primary" type="submit">کاربر معمولی</button></a>
          {% endif %}
            {% else %}
            <a href="{% url 'accounts:login' %}"><button class="btn btn-outline-success" type="submit">ورود</button></a>
            <a href="{% url 'accounts:register' %}"><button class="btn btn-outline-success" type="submit">ثبت نام</button></a>
          {% endif %}  
          
        </div>
      </div>
    </nav>
    {% if messages %}

		{% for message in messages %}
			<p  class="alert alert-{{ message.tags }}">{{ message }}</p>
		{% endfor %}

	{% endif %}          
              
                
      <!--END NAVBAR-->

    <div >
      {% block content %}

      {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  
</body>
</html>

register/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>خانه</h1>
{% endblock content %}
    

register/templates/login.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="ورود">
    </form>
    
{% endblock content %}
    

register/templates/register.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="ثبت نام">
    </form>
    
{% endblock content %}
    

register/templates/verify.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="ارسال کد">
    </form>
    
{% endblock content %}
    